//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Excalibur {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://3gbywork.github.io/schema/ConsoleConfig.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://3gbywork.github.io/schema/ConsoleConfig.xsd", IsNullable=false)]
    public partial class Agents {
        
        private AgentsAgent[] agentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Agent")]
        public AgentsAgent[] Agent {
            get {
                return this.agentField;
            }
            set {
                this.agentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://3gbywork.github.io/schema/ConsoleConfig.xsd")]
    public partial class AgentsAgent {
        
        private string nameField;
        
        private string pathField;
        
        private string paramField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Param {
            get {
                return this.paramField;
            }
            set {
                this.paramField = value;
            }
        }
    }
}
